FROM python:3.11-slim

WORKDIR /bot

COPY requirements.txt .

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY ./bot .

CMD ["python", "-m", "bot.main"]
